/* ABISHEK STUDIO — STABLE PHOTOGRAPHY FILTER + SAFE PAGINATION */
(function(){
'use strict';
const LABELS={all:'All',street:'Street',covers:'Covers',picsarts:'Picsarts',posters:'Posters'};
const PAGE_SIZE=4;let active='all',visibleCount=PAGE_SIZE;
const normalize=v=>String(v??'').toLowerCase().trim().replace(/[\s_-]+/g,'');
const canonical=v=>{const x=normalize(v);if(x==='street'||x==='streetphotography'||x==='streetphoto')return'street';if(x==='cover'||x==='covers'||x==='coverphoto'||x==='coverphotos')return'covers';if(x==='picsart'||x==='picsarts'||x==='picsartphoto'||x==='picsartphotos')return'picsarts';if(x==='poster'||x==='posters'||x==='posterphoto'||x==='posterphotos')return'posters';return x==='all'?'all':x};
const data=()=>Array.isArray(window.galleryData)?window.galleryData:(typeof galleryData!=='undefined'?galleryData:[]);
const listFor=cat=>{const c=canonical(cat);return data().filter(item=>c==='all'||canonical(item.cat)===c)};
const galleryEl=()=>document.getElementById('gallery');const barEl=()=>document.getElementById('filter-bar');
function setupButtons(){const bar=barEl();if(!bar)return;bar.querySelectorAll('.filter-btn').forEach(btn=>{const c=canonical(btn.dataset.cat||btn.textContent||'all');btn.dataset.cat=c;btn.textContent=LABELS[c]||btn.textContent})}
function makeCard(item,index){const all=data(),gid=all.indexOf(item),fav=typeof isFavorited==='function'&&isFavorited(gid),src=typeof IMG==='function'?IMG(item.img||'',700):(item.img||'');const card=document.createElement('div');card.className='g-card reveal';card.dataset.gid=gid;card.dataset.category=canonical(item.cat);card.dataset.idx=index;card.innerHTML=`<div class="g-card-img"><img src="${src}" alt="${item.title||''}" loading="lazy" style="height:${item.h||520}px;object-fit:cover;display:block;width:100%"><button class="g-fav-badge${fav?' favorited':''}" data-act="favorite" aria-label="Favorite this photo"><svg width="16" height="16" viewBox="0 0 24 24" fill="${fav?'currentColor':'none'}" stroke="currentColor" stroke-width="2"><path d="M20.8 4.6a5 5 0 00-7.1 0L12 6.3l-1.7-1.7a5 5 0 00-7.1 7.1L12 21l8.8-9.3a5 5 0 000-7.1z"/></svg></button><div class="g-overlay"><div class="g-cat">${item.cat||''}</div><div class="g-title">${item.title||''}</div><div class="g-loc">${item.loc||''} · ${item.date||''}</div></div></div><div class="g-dots" aria-label="Photo menu" role="button" tabindex="0"><svg viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="19" cy="12" r="2"/></svg></div><div class="g-menu"><button data-act="view">View Details</button><button data-act="share">Share</button><button data-act="download">Download</button><button class="fav-menu-item${fav?' favorited':''}" data-act="favorite">${fav?'Favorited':'Favorite'}</button></div>`;if(typeof withFallback==='function')withFallback(card.querySelector('img'),'gal-'+gid);return card}
function removeMore(){document.querySelectorAll('#load-more-btn,.view-more-wrap').forEach(el=>el.remove())}
function updateMore(total){removeMore();if(visibleCount>=total)return;const btn=document.createElement('button');btn.id='load-more-btn';btn.type='button';btn.className='btn-outline load-more-btn';btn.textContent='View More';const wrap=document.createElement('div');wrap.className='view-more-wrap';wrap.appendChild(btn);(galleryEl()?.parentElement||document.body).appendChild(wrap)}
function render(){const g=galleryEl();if(!g)return;const selected=listFor(active);g.innerHTML='';selected.slice(0,visibleCount).forEach((item,i)=>g.appendChild(makeCard(item,i)));updateMore(selected.length);if(typeof refreshRevealTargets==='function')refreshRevealTargets();if(typeof bindMagnetic==='function')bindMagnetic()}
function choose(cat){active=canonical(cat||'all');visibleCount=PAGE_SIZE;const bar=barEl();bar?.querySelectorAll('.filter-btn').forEach(btn=>btn.classList.toggle('active',canonical(btn.dataset.cat)===active));render()}
function bind(){setupButtons();const bar=barEl();if(bar&&!bar.dataset.stablePhotographyFilter){bar.dataset.stablePhotographyFilter='1';bar.addEventListener('click',e=>{const btn=e.target.closest('.filter-btn');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();choose(btn.dataset.cat||'all')},true)}if(!document.documentElement.dataset.stablePhotographyMore){document.documentElement.dataset.stablePhotographyMore='1';document.addEventListener('click',e=>{const btn=e.target.closest('#load-more-btn');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();const total=listFor(active).length;if(visibleCount<total){visibleCount=Math.min(visibleCount+PAGE_SIZE,total);render()}},true)}const initial=bar?.querySelector('.filter-btn.active')?.dataset.cat||'all';choose(initial)}
function wait(){setupButtons();if(!galleryEl()||typeof galleryData==='undefined'){setTimeout(wait,100);return}bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait);else wait();
})();